### ISSUE TITLE
InaccessibleObjectException using Java 16

### ISSUE THREAD

**Issue by DaveJarvis** [FXMisc/RichTextFX#1013]
Using Java 16 ([full edition](https://bell-sw.com/pages/downloads/)):

``` plain
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make com.sun.javafx.scene.text.TextLayout javafx.scene.text.TextFlow.getTextLayout() accessible: module javafx.graphics does not "opens javafx.scene.text" to unnamed module @80d6b77
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at org.fxmisc.richtext.TextFlowExt.<clinit>(TextFlowExt.java:37)
	... 43 more
```

The offending lines appear to be in `TextFlowExt.java`:

``` java
class TextFlowExt extends TextFlow {

    private static Method mGetTextLayout;
    static {
        try {
            mGetTextLayout = TextFlow.class.getDeclaredMethod("getTextLayout");
        } catch (NoSuchMethodException | SecurityException e) {
            throw new RuntimeException(e);
        }
        mGetTextLayout.setAccessible(true);
    }
```

The `build.gradle` file includes:

``` groovy
application {
  applicationName = config["application.title"].toLowerCase()
  mainClass.set("com.${applicationName}.Main")

  applicationDefaultJvmArgs = [
    "--add-opens=javafx.controls/javafx.scene.control=ALL-UNNAMED",
    "--add-opens=javafx.controls/javafx.scene.control.skin=ALL-UNNAMED",
    "--add-opens=javafx.graphics/javafx.scene.text=ALL-UNNAMED",
    "--add-opens=javafx.graphics/com.sun.javafx.css=ALL-UNNAMED",
    "--add-opens=javafx.graphics/com.sun.javafx.text=ALL-UNNAMED",
    "--add-exports=javafx.graphics/com.sun.javafx.application=ALL-UNNAMED",
    "--add-exports=javafx.graphics/com.sun.javafx.geom=ALL-UNNAMED",
    "--add-exports=javafx.graphics/com.sun.javafx.text=ALL-UNNAMED",
  ]
}
```

Running with `--illegal-access=permit` reveals:

``` plain
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.fxmisc.richtext.TextFlowExt (file:keenwrite.jar) to method javafx.scene.text.TextFlow.getTextLayout()
WARNING: Please consider reporting this to the maintainers of org.fxmisc.richtext.TextFlowExt
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Additional trace:

``` plain
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.ExceptionInInitializerError
	at org.fxmisc.richtext.ParagraphBox.<init>(ParagraphBox.java:98)
	at org.fxmisc.richtext.GenericStyledArea.createCell(GenericStyledArea.java:1813)
	at org.fxmisc.richtext.GenericStyledArea.lambda$new$11(GenericStyledArea.java:764)
	at org.fxmisc.flowless.CellPool.getCell(CellPool.java:28)
	at org.fxmisc.flowless.CellListManager.cellForItem(CellListManager.java:90)
	at org.reactfx.collection.MappedList.get(MappedList.java:27)
	at org.reactfx.collection.MemoizationListImpl.get(MemoizationList.java:99)
	at org.fxmisc.flowless.CellListManager.getCell(CellListManager.java:73)
	at org.fxmisc.flowless.CellPositioner.getSizedCell(CellPositioner.java:217)
	at org.fxmisc.flowless.CellPositioner.placeStartAt(CellPositioner.java:127)
	at org.fxmisc.flowless.Navigator.visit(Navigator.java:131)
	at org.fxmisc.flowless.StartOffStart.accept(TargetPosition.java:85)
	at org.fxmisc.flowless.Navigator.layoutChildren(Navigator.java:80)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1207)
	at org.fxmisc.flowless.VirtualFlow.layoutChildren(VirtualFlow.java:257)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1207)
	at org.fxmisc.flowless.VirtualFlow.visibleCells(VirtualFlow.java:230)
	at org.fxmisc.richtext.GenericStyledArea.<init>(GenericStyledArea.java:801)
	at org.fxmisc.richtext.StyledTextArea.<init>(StyledTextArea.java:33)
	at org.fxmisc.richtext.StyledTextArea.<init>(StyledTextArea.java:45)
	at org.fxmisc.richtext.StyleClassedTextArea.<init>(StyleClassedTextArea.java:21)
	at org.fxmisc.richtext.StyleClassedTextArea.<init>(StyleClassedTextArea.java:34)
```

**Comment by Jugen** [comment]
Are you compiling RichTextFX yourself or using an official build ?
If an official build which Jar are you using ?

**Comment by DaveJarvis** [comment]
``` groovy
javafx {
  version = "16"
  modules = ['javafx.controls', 'javafx.swing']
  configuration = 'compileOnly'
}

dependencies {
  implementation 'org.controlsfx:controlsfx:11.1.0'
  implementation 'org.fxmisc.richtext:richtextfx:0.10.6'
  implementation 'org.fxmisc.wellbehaved:wellbehavedfx:0.3.3'
  implementation 'com.miglayout:miglayout-javafx:5.2'
  implementation 'com.dlsc.preferencesfx:preferencesfx-core:11.8.0'
}
```

Using [Liberica OpenJDK](https://bell-sw.com/pages/downloads/):

``` bash
$ java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9)
OpenJDK 64-Bit Server VM (build 16.0.1+9, mixed mode, sharing)
```

**Comment by Jugen** [comment]
So that's really weird, because the 0.10.6 jar is a multi-release jar. The JVM is loading the default `TextFlowExt.class` file, whereas the it should be loading the class from the `META-INF\versions\9\` folder in the jar.

Here's a modified jar (just rename zip to jar) where I've changed the folder to 16 instead: [richtextfx-0.10.6.zip](https://github.com/FXMisc/RichTextFX/files/6422599/richtextfx-0.10.6.zip)
Could you give that a try and see what happens.

**Comment by DaveJarvis** [comment]
``` groovy
  // JavaFX
  implementation 'org.controlsfx:controlsfx:11.1.0'
  //implementation 'org.fxmisc.richtext:richtextfx:0.10.6'
  implementation 'org.fxmisc.flowless:flowless:0.6.3'
  implementation 'org.fxmisc.undo:undofx:2.1.1'
```

Looks good, up until ControlsFX:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by impl.org.controlsfx.ReflectionUtils (file:controlsfx-11.1.0.jar) to method com.sun.javafx.scene.ParentHelper.setTraversalEngine(javafx.scene.Parent,com.sun.javafx.scene.traversal.ParentTraversalEngine)
WARNING: Please consider reporting this to the maintainers of impl.org.controlsfx.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

But that can be a separate ticket.

**Comment by Jugen** [comment]
Okay, thanks for the feedback.  I'm going to have to figure out why it's not behaving as I expect it too.
My understanding was that the JVM would, with a multi-release jar, use the highest / closest version to it.

**Comment by Jugen** [comment]
Okay, so I've done some tests with various Java versions (including from Liberica) and they all behave exactly as expected with the original unaltered multi-release jar file. So I'm still at a loss as to why it misbehaved in your case ?

**Comment by DaveJarvis** [comment]
> So I'm still at a loss as to why it misbehaved in your case ?

Could it be the difference between a modular and non-modular app?

**Comment by Jugen** [comment]
I had the same idea and tried that as well, and it worked as expected ?

**Comment by DaveJarvis** [comment]
> I had the same idea and tried that as well, and it worked as expected ?

A stretch: dependency interaction? Could one of the other JavaFX dependencies be influencing TextFlowExt's library?

**Comment by DaveJarvis** [comment]
Cannot replicate.
