### ISSUE TITLE
Visible paragraphs' last index is [-1] but visibleParIndex was [0]

### ISSUE THREAD

**Issue by fangzhongwei** [FXMisc/RichTextFX#1042]
1.Run JavaKeywordsDemo to open the "Java Keywords Demo".
2.Copy one line text, such as "System.err.println("Warning: empty string as argument");".
3.Press Ctrl + A to select whole text, then Press Ctrl + V to paste, got follow error.
4.It only happens when paste for the first time.

Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: Visible paragraphs' last index is [-1] but visibleParIndex was [0]
	at org.fxmisc.richtext.GenericStyledArea.visibleParToAllParIndex(GenericStyledArea.java:982)
	at org.fxmisc.richtext.ViewActions.firstVisibleParToAllParIndex(ViewActions.java:284)
	at org.fxmisc.richtext.LineNumberFactory.deleteParagraphCheck(LineNumberFactory.java:148)
	at org.fxmisc.richtext.LineNumberFactory.lambda$new$1(LineNumberFactory.java:91)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run$$$capture(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Siedlerchr** [comment]
Yep, We encountered the same with the XML Editor highlighting https://github.com/JabRef/jabref/issues/7860

**Comment by Siedlerchr** [comment]
Seems like its's already fixed in master https://github.com/FXMisc/RichTextFX/issues/1021
