### ISSUE TITLE
This ParagraphText is not the parent of the given shape

### ISSUE THREAD

**Issue by Lson-L** [FXMisc/RichTextFX#1048]
I want use richTextFx to get CaretBounds with follow code

```
CodeArea codeArea = new CodeArea();
codeArea.textProperty().addListener(new ChangeListener<String>() {
            @Override
            public void changed(ObservableValue<? extends String> observable, String oldValue, String newValue) {
                Optional<Bounds> optional = codeArea.getCaretBounds();
                optional.ifPresent(bounds -> {
                    System.out.println(bounds);
                });

            }
        });
```

My Textarea has some letter like `"a \n b"`,when I delete `\n b` back to `a` then `codeArea.getCaretBounds();` throw error 
```
Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: This ParagraphText is not the parent of the given shape (CaretNode(name=main-caret position=1 paragraphIndex=0 columnPosition=1 Path[elements=[MoveTo[x=0.0, y=0.0], LineTo[x=0.0, y=15.0]], fill=null, fillRule=NON_ZERO, stroke=0x000000ff, strokeWidth=1.0])):
Expected: ParagraphText@696605963(paragraph=Par[[]; StyledSegment(segment=a style=[])])
Actual:   null
	at org.fxmisc.richtext.ParagraphText.checkWithinParagraph(ParagraphText.java:311)
	at org.fxmisc.richtext.ParagraphText.getCaretBoundsOnScreen(ParagraphText.java:256)
	at org.fxmisc.richtext.ParagraphBox.getCaretBoundsOnScreen(ParagraphBox.java:214)
	at org.fxmisc.richtext.GenericStyledArea.lambda$getCaretBoundsOnScreen$24(GenericStyledArea.java:1197)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.fxmisc.richtext.GenericStyledArea.getCaretBoundsOnScreen(GenericStyledArea.java:1197)
	at org.fxmisc.richtext.CaretNode.lambda$new$6(CaretNode.java:233)
	at org.reactfx.value.Val$3.computeValue(Val.java:722)
	at org.reactfx.value.ValBase.getValue(ValBase.java:17)
	at org.reactfx.value.SuspendableValWrapper.getValue(SuspendableValWrapper.java:23)
	at org.fxmisc.richtext.CaretNode.getCaretBounds(CaretNode.java:103)
	at org.fxmisc.richtext.CaretSelectionBindImpl.getCaretBounds(CaretSelectionBindImpl.java:60)
	at org.fxmisc.richtext.TextEditingArea.getCaretBounds(TextEditingArea.java:101)
	at com.erayt.studio.test.JavaKeywordsDemo$1.changed(JavaKeywordsDemo.java:158)
	at com.erayt.studio.test.JavaKeywordsDemo$1.changed(JavaKeywordsDemo.java:155)
```
How can I get right CaretBounds ?

Environment:
JAVA:11 
richtextfx:0.10.7

**Comment by Jugen** [comment]
I've submitted a PR to fix this which you can try and use or you can use the following until the next release:

```java
codeArea.textProperty().addListener( (ob,ov,nv) -> Platform.runLater( () ->
{
    Optional<Bounds> optional = codeArea.getCaretBounds();
    optional.ifPresent(bounds -> System.out.println(bounds) );
}));
```
