### ISSUE TITLE
textArea.getCharacterBoundsOnScreen(i, i) gives inappropriate bounds or throws IndexOutOfBoundsException

### ISSUE THREAD

**Issue by willplatt** [FXMisc/RichTextFX#1073]
## Expected Behavior

Calling `textArea.getCharacterBoundsOnScreen(i, i)` should return appropriate bounds (e.g. the bounds a caret would have if it were at position `i`) or throw an IllegalArgumentException if the method is not intended to accept equal parameters (in which case there ought to be some other way to get bounds for an hypothetical caret).

## Actual Behavior

The same 1x1 bounds are returned for all values of `i`, and if `i` is the length of the text then an `IndexOutOfBoundsException` is thrown due to the method calling `getText(i, i+1)`:

```
549.0-550.0, 204.0-205.0
549.0-550.0, 204.0-205.0
549.0-550.0, 204.0-205.0
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Position 4 is out of bounds
	at org.reactfx.util.FingerTree$NonEmptyFingerTree.locate(FingerTree.java:42)
	at org.fxmisc.richtext.model.ReadOnlyStyledDocument.split(ReadOnlyStyledDocument.java:278)
	at org.fxmisc.richtext.model.ReadOnlyStyledDocument.subSequence(ReadOnlyStyledDocument.java:318)
	at org.fxmisc.richtext.model.GenericEditableStyledDocumentBase.subSequence(GenericEditableStyledDocumentBase.java:196)
	at org.fxmisc.richtext.model.SimpleEditableStyledDocument.subSequence(SimpleEditableStyledDocument.java:10)
	at org.fxmisc.richtext.model.StyledDocument.getText(StyledDocument.java:35)
	at org.fxmisc.richtext.GenericStyledArea.getText(GenericStyledArea.java:1083)
	at org.fxmisc.richtext.GenericStyledArea.getCharacterBoundsOnScreen(GenericStyledArea.java:1045)
	at GetCharacterBoundsBug.lambda$start$0(GetCharacterBoundsBug.java:23)
```

## Reproducible Demo

```
import javafx.application.Application;
import javafx.geometry.Bounds;
import javafx.scene.Scene;
import javafx.stage.Stage;
import org.fxmisc.richtext.StyleClassedTextArea;

public class GetCharacterBoundsBug extends Application {
	
	public static void main(String[] args) {
		GetCharacterBoundsBug.launch(args);
	}
	
	@Override
	public void start(Stage stage) {
		StyleClassedTextArea textArea = new StyleClassedTextArea();
		String text = "Abc";
		textArea.append(text, "");
		Scene scene = new Scene(textArea, 500, 300);
		stage.setScene(scene);
		stage.show();
		textArea.setOnMouseClicked(mouseEvent -> {
			for (int i = 0; i <= textArea.getLength(); i++) {
				Bounds bounds = textArea.getCharacterBoundsOnScreen(i, i).get();
				System.out.println(bounds.getMinX() + "-" + bounds.getMaxX() + ", " + bounds.getMinY() + "-" + bounds.getMaxY());
			}
		});
	}
	
	public static class Launcher {
		public static void main(String[] args) {
			GetCharacterBoundsBug.main(args);
		}
	}
}
```

## Environment info:

- RichTextFX Version: 0.10.7
- Operating System: Windows 10
- Java version: 11.0.1
- JavaFX version: 17.0.1

<hr>

## Current Workarounds

If `textArea.length()` > 0 then get the bounds between `i-1` and `i` or `i` and `i+1` and change the max/min x value to give bounds of the width you expect.

If `textArea.length()` is 0 then I'm not aware of an easy solution. If you know the caret is showing then use `textArea.getCaretBounds()`. Otherwise, briefly add text to get the bounds and then delete the text, or try to approximate the bounds for position 0 using the bounds of the text area and padding information.

**Comment by Jugen** [comment]
Thanks for reporting and especially the demo, it helped a lot !
I've submitted a PR to resolve this.
