### ISSUE TITLE
Double clicking in CodeArea should work as expected

### ISSUE THREAD

**Issue by effad** [FXMisc/RichTextFX#1087]
## Expected Behavior

Given the code:
```
		myStr.substring(2)
```
double clicking myStr should select myStr.

## Actual Behavior

Currently myStr.substring is selected. This is unexpected, since most modern programming languages use the dot as separator between identifiers.

What is more, this behaviour cannot easily be adapted, since word-boundary detection happens with locales and BreakIterator internally. Overwriting CodeArea.selectWord() is of course an option, but since CodeArea already overrides the default behaviour of its superclass to include underscored words it should really happen there, I think.

## Reproducible Demo

Can be reproduced with any demo that uses CodeArea.

## Environment info:

- RichTextFX Version: 0.10.7
- Operating System: Linux, Fedora 34
- Java version: 17.0.1+12

**Comment by effad** [comment]
I just noticed that a similar problem is also present when navigating with Ctrl-Left and Ctrl-Right. The word boundaries delivered by the BreakIterator are not well suited to programming languages, it seems.
Maybe a custom BreakIterator (plus some API to be able to set it) is required?

**Comment by effad** [comment]
I just tried to work with what is there and created a custom BreakIteratorProvider (which will only be taken into account if the system property `java.locale.providers` contains SPI) that will support a fictitious locale and provide word breaks that are consistent with what is expected in a code editor.
To "activate" it, I called `org.fxmisc.richtext.GenericStyledArea.setLocale(Locale)`. This will work with `org.fxmisc.richtext.CodeArea.selectWord()` but **not** with `org.fxmisc.richtext.NavigationActions.wordBreaksForwards(int, SelectionPolicy)`, because the former uses `BreakIterator.getWordInstance( getLocale() )`, while the latter only calls `BreakIterator.getWordInstance()`, which will in turn get the word break iterator for the default locale.

So even with the huge (mental) overhead that Java SPI brings along it is not possible to cleanly apply a new word break strategy.

**Comment by Jugen** [comment]
Okay, for starters I've submitted a PR to fix `wordBreaksForwards` not using the Locale.

Then I'm also looking at replacing CodeArea's use of _BreakIterator_ (which the JavaDocs explicitly say "are intended for use with natural languages only, not for programming language text"). So I think we can override `selectWord` as well as `wordBreaksForwards` & `wordBreaksBackwards` with a RegEx implementation instead. 

You are are welcome to submit a PR if you want, otherwise I would appreciate seeing your custom BreakIterator.
At the moment I'm just using:
```java
private final Pattern WORD_PATTERN = Pattern.compile( "\\w+" );
private final Pattern WORD_SPACE = Pattern.compile( "\\w*\\h*" );
```

**Comment by effad** [comment]
Your change to use a regexp is a much better approach for CodeArea than Locale/BreakIterator. Since the new methods can be overridden it is also much easier to customize the behaviour programmatically.

FWIW here's my BreakIteratorProvider:
```
import java.text.BreakIterator;
import java.text.spi.BreakIteratorProvider;
import java.util.Locale;

public class GroovyBreakIteratorProvider extends BreakIteratorProvider {

	@Override
	public BreakIterator getWordInstance(Locale locale) {
		return new GroovyWordBreakIterator();
	}

	@Override
	public BreakIterator getLineInstance(Locale locale) {
		return BreakIterator.getLineInstance(Locale.ENGLISH);
	}

	@Override
	public BreakIterator getCharacterInstance(Locale locale) {
		return BreakIterator.getCharacterInstance(Locale.ENGLISH);
	}

	@Override
	public BreakIterator getSentenceInstance(Locale locale) {
		return BreakIterator.getSentenceInstance(Locale.ENGLISH);
	}

	@Override
	public Locale[] getAvailableLocales() {
		return new Locale[] { new Locale("groovy") };
	}
}
```
and the BreakIterator itself (unfinished!):
```import java.text.BreakIterator;
import java.text.CharacterIterator;

public class GroovyWordBreakIterator extends BreakIterator {

	private CharacterIterator text;
	
	private enum CharClass {
		WORD,
		NONWORD,
		WHITESPACE
	}
	
	@Override
	public int first() {
		text.setIndex(text.getBeginIndex());
		return text.getIndex();
	}

	@Override
	public int last() {
		text.setIndex(text.getEndIndex());
		return text.getIndex();
	}

	@Override
	public int next(int n) {
		for (int i = 0; i < n; i++) {
			next();
		}
		return text.getIndex();
	}

	@Override
	public int next() {
		GroovyWordBreakIterator.CharClass startClz = getCharclass(text.current());
		GroovyWordBreakIterator.CharClass curClz = startClz;
		while (curClz == startClz || curClz == CharClass.WHITESPACE) {
			curClz = getCharclass(text.next());
		}
		return text.getIndex();
	}

	@Override
	public int previous() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int following(int offset) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int current() {
		return text.getIndex();
	}

	@Override
	public CharacterIterator getText() {
		return text;
	}

	@Override
	public void setText(CharacterIterator newText) {
		this.text = newText;
	}
	
	private GroovyWordBreakIterator.CharClass getCharclass(char c) {
		GroovyWordBreakIterator.CharClass clz = CharClass.NONWORD;
		if (Character.isJavaIdentifierPart(c)) {
			clz = CharClass.WORD;
		} else if (Character.isWhitespace(c)) {
			clz = CharClass.WHITESPACE;				
		}
		return clz;
	}
}
```
Ignore the "Groovy"-Prefix please :-)

As you can see I am working without regular expressions but use 3 different "character classes" (WORD, NONWORD, WHITESPACE). This is necessary to emulate the behaviour of e.g. gedit (and other common editors), that is expressed in the following test:
```
public class GroovyWordBreakIteratorTest {
	
	private static final String TEST1 = "if (foo.bar()  == mmo)";

	@Test
	public void testWordJumps() {
		GroovyWordBreakIterator gwbi = new GroovyWordBreakIterator();
		gwbi.setText(TEST1);
		
		Assert.assertEquals(gwbi.current(), 0);
		Assert.assertEquals(gwbi.next(), 3); // before the first (
		Assert.assertEquals(gwbi.next(), 4); // before the f in foo
		Assert.assertEquals(gwbi.next(), 7); // right after foo
		Assert.assertEquals(gwbi.next(), 8); // right before bar
		Assert.assertEquals(gwbi.next(), 11); // right after bar
		Assert.assertEquals(gwbi.next(), 15); // right before ==
		Assert.assertEquals(gwbi.next(), 18); // right before mmo
		Assert.assertEquals(gwbi.next(), 21); // right after mmo
		Assert.assertEquals(gwbi.next(), 22); // right after )
		Assert.assertEquals(gwbi.next(), BreakIterator.DONE); 
	}
}
```

**Comment by effad** [comment]
Note that `testWordJumps` will fail ATM since it won't stop "right before mmo".

**Comment by Jugen** [comment]
Great, thanks for the code above.
I've updated the PR so that the regex now skips over double symbols like:  !=  <=  >=  ==  && ||  etc.
So the proposed implementation now passes your simple test case. 
Please review and comment.

**Comment by effad** [comment]
I've just tried to take a look at your changes but came across Issue #1094.

**Comment by Jugen** [comment]
Can you try this then: [richtextfx-0.10.8-rc1.zip](https://github.com/FXMisc/RichTextFX/files/8088669/richtextfx-0.10.8-rc1.zip)
(Just rename zip to jar)

**Comment by effad** [comment]
> Can you try this then: [richtextfx-0.10.8-rc1.zip](https://github.com/FXMisc/RichTextFX/files/8088669/richtextfx-0.10.8-rc1.zip) (Just rename zip to jar)

I couldn't use this easily, since the dependencies are missing. Using the .jar - Files from 0.10.7 like this:
```
java -cp wellbehavedfx-0.3.3.jar:undofx-2.1.1.jar:reactfx-2.0-M5.jar:richtextfx-0.10.8-rc1.jar:flowless-0.6.7.jar:. XMLEditorDemo
```
gives me:
```
Exception in Application start method
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$417(LauncherImpl.java:182)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.fxmisc.flowless.VirtualizedScrollPane.snapSizeX(D)D
        at org.fxmisc.flowless.VirtualizedScrollPane.layoutChildren(VirtualizedScrollPane.java:298)
        at javafx.scene.Parent.layout(Parent.java:1087)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Scene.doLayoutPass(Scene.java:552)
        at javafx.scene.Scene.preferredSize(Scene.java:1646)
        at javafx.scene.Scene.impl_preferredSize(Scene.java:1720)
        at javafx.stage.Window$9.invalidated(Window.java:864)
        at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
        at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
        at javafx.stage.Window.setShowing(Window.java:940)
        at javafx.stage.Window.show(Window.java:955)
        at javafx.stage.Stage.show(Stage.java:259)
        at XMLEditorDemo.start(XMLEditorDemo.java:86)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$424(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$404(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$402(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$403(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$208(GtkApplication.java:245)
        ... 1 more
Exception running application XMLEditorDemo
```

**Comment by effad** [comment]
I still get:
```
[rli@rlimbus Downloads]$ java -cp richtextfx-fat-0.10.8-rc1.jar:. XMLEditorDemo 
Exception in Application start method
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$417(LauncherImpl.java:182)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.fxmisc.flowless.VirtualizedScrollPane.snapSizeX(D)D
        at org.fxmisc.flowless.VirtualizedScrollPane.layoutChildren(VirtualizedScrollPane.java:298)
        at javafx.scene.Parent.layout(Parent.java:1087)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Scene.doLayoutPass(Scene.java:552)
        at javafx.scene.Scene.preferredSize(Scene.java:1646)
        at javafx.scene.Scene.impl_preferredSize(Scene.java:1720)
        at javafx.stage.Window$9.invalidated(Window.java:864)
        at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
        at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
        at javafx.stage.Window.setShowing(Window.java:940)
        at javafx.stage.Window.show(Window.java:955)
        at javafx.stage.Stage.show(Stage.java:259)
        at XMLEditorDemo.start(XMLEditorDemo.java:86)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$424(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$404(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$402(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$403(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$208(GtkApplication.java:245)
        ... 1 more
```

**Comment by effad** [comment]
> Can you change Java versions ? If you want a JDK that includes JavaFX you can try either [Azul](https://www.azul.com/downloads/?package=jre-fx) or [BellSoft](https://bell-sw.com/pages/downloads/?package=jre-full)
Good idea, so yes I got it working with BellSoft and it works like a charm -- feels much more natural that way.

Thank you very much for your efforts, can't wait for a new version to be released :-).
