### ISSUE TITLE
StyleClassedTextArea.copy() sometimes gives exception

### ISSUE THREAD

**Issue by PashaTurok** [FXMisc/RichTextFX#1118]
I have a StyleClassedTextArea with about 1000 lines of log messages. Levels (debug/trace etc) of the message has different style classes (to show levels with different colors). For example, when I select this text:

```
2022-06-19 18:15:20.909 [DEBUG] [main] org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider - Class, class org.glassfish.jersey.ext.cdi1x.servlet.internal.CdiExternalRequestScope, is being checked with Jersey CDI component provider.
2022-06-19 18:15:20.918 [DEBUG] [main] org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider - Class, class org.apache.shiro.web.jaxrs.ShiroAnnotationFilterFeature, is being checked with Jersey CDI component provider.
```

And click copy button I get this exception:

```
2022-06-19 18:15:36.454 [ERROR] [JavaFX Application Thread] npd.kit.fx.FxPlatform - Error in FxApplication
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:359) ~[?:?]
	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:333) ~[?:?]
	at org.fxmisc.richtext.model.Codec$1.encode(Codec.java:35) ~[richtextfx-0.10.9.jar:?]
	at org.fxmisc.richtext.model.Codec$1.encode(Codec.java:26) ~[richtextfx-0.10.9.jar:?]
	at org.fxmisc.richtext.model.SuperCodec$1.encodeSuper(SuperCodec.java:44) ~[richtextfx-0.10.9.jar:?]
	at org.fxmisc.richtext.model.SuperCodec$1.encodeSuper(SuperCodec.java:33) ~[richtextfx-0.10.9.jar:?]
	at org.fxmisc.richtext.model.SuperCodec.encode(SuperCodec.java:21) ~[richtextfx-0.10.9.jar:?]
	at org.fxmisc.richtext.model.Codec$4.encode(Codec.java:103) ~[richtextfx-0.10.9.jar:?]
	at org.fxmisc.richtext.model.Codec$4.encode(Codec.java:94) ~[richtextfx-0.10.9.jar:?]
	at org.fxmisc.richtext.model.SuperCodec$1.encodeSuper(SuperCodec.java:44) ~[richtextfx-0.10.9.jar:?]
	at org.fxmisc.richtext.model.SuperCodec$1.encodeSuper(SuperCodec.java:33) ~[richtextfx-0.10.9.jar:?]
	at org.fxmisc.richtext.model.SuperCodec.encode(SuperCodec.java:21) ~[richtextfx-0.10.9.jar:?]
	at org.fxmisc.richtext.model.ReadOnlyStyledDocument$3.encode(ReadOnlyStyledDocument.java:203) ~[richtextfx-0.10.9.jar:?]
	at org.fxmisc.richtext.model.ReadOnlyStyledDocument$3.encode(ReadOnlyStyledDocument.java:192) ~[richtextfx-0.10.9.jar:?]
	at org.fxmisc.richtext.model.SuperCodec$1.encodeSuper(SuperCodec.java:44) ~[richtextfx-0.10.9.jar:?]
	at org.fxmisc.richtext.model.SuperCodec$1.encodeSuper(SuperCodec.java:33) ~[richtextfx-0.10.9.jar:?]
	at org.fxmisc.richtext.model.SuperCodec.encode(SuperCodec.java:21) ~[richtextfx-0.10.9.jar:?]
	at org.fxmisc.richtext.model.ReadOnlyStyledDocument$2.encode(ReadOnlyStyledDocument.java:178) ~[richtextfx-0.10.9.jar:?]
	at org.fxmisc.richtext.model.ReadOnlyStyledDocument$2.encode(ReadOnlyStyledDocument.java:166) ~[richtextfx-0.10.9.jar:?]
	at org.fxmisc.richtext.ClipboardActions.lambda$copy$0(ClipboardActions.java:66) ~[richtextfx-0.10.9.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at org.fxmisc.richtext.ClipboardActions.copy(ClipboardActions.java:59) ~[richtextfx-0.10.9.jar:?]
	at npd.console.gui.application.ApplicationModel.lambda$new$12(ApplicationModel.java:90) ~[npd-console-gui-1.0.0.jar:?]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) ~[javafx-base-19-ea+3-linux.jar:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234) ~[javafx-base-19-ea+3-linux.jar:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[javafx-base-19-ea+3-linux.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[javafx-base-19-ea+3-linux.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[javafx-base-19-ea+3-linux.jar:?]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[javafx-base-19-ea+3-linux.jar:?]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49) ~[javafx-base-19-ea+3-linux.jar:?]
	at javafx.event.Event.fireEvent(Event.java:198) ~[javafx-base-19-ea+3-linux.jar:?]
	at javafx.scene.control.MenuItem.fire(MenuItem.java:459) ~[javafx-controls-19-ea+3-linux.jar:?]
	at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1385) ~[javafx-controls-19-ea+3-linux.jar:?]
	at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1338) ~[javafx-controls-19-ea+3-linux.jar:?]
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247) ~[javafx-base-19-ea+3-linux.jar:?]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80) ~[javafx-base-19-ea+3-linux.jar:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234) ~[javafx-base-19-ea+3-linux.jar:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[javafx-base-19-ea+3-linux.jar:?]
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) ~[javafx-base-19-ea+3-linux.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[javafx-base-19-ea+3-linux.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[javafx-base-19-ea+3-linux.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[javafx-base-19-ea+3-linux.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[javafx-base-19-ea+3-linux.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[javafx-base-19-ea+3-linux.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[javafx-base-19-ea+3-linux.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[javafx-base-19-ea+3-linux.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[javafx-base-19-ea+3-linux.jar:?]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[javafx-base-19-ea+3-linux.jar:?]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) ~[javafx-base-19-ea+3-linux.jar:?]
	at javafx.event.Event.fireEvent(Event.java:198) ~[javafx-base-19-ea+3-linux.jar:?]
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3881) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at javafx.scene.Scene.processMouseEvent(Scene.java:1874) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2607) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at com.sun.glass.ui.View.handleMouseEvent(View.java:551) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at com.sun.glass.ui.View.notifyMouse(View.java:937) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
At the same time I can't reproduce this exception. Sometimes it works, sometimes it doesn't.

**Comment by PashaTurok** [comment]
I found out that this happens if `textArea.append(text, styleClass);` and `styleClass` is null.

**Comment by Jugen** [comment]
Umm, so although null can technically be encoded on the DataOutputStream ..... the problem comes when decoding as null usually indicates the end of the input stream. This basically means, I think, that style cannot be null.

I've submitted a PR that will check for null styles in future and behave like `replaceText` if the style is null.

In the meantime you'll need to do something like:
```java
if ( styleClass == null ) textArea.appendText( text );
else textArea.append( text, styleClass );
```
alternatively  you could also try:
```java
if ( styleClass == null ) styleClass = Collections.EMPTY;
textArea.append( text, styleClass );
```
