### ISSUE TITLE
Getting No toolkit found in intellij

### ISSUE THREAD

**Issue by ozkanpakdil** [FXMisc/RichTextFX#1186]
## trying to build a ui something similar to postman

https://github-production-user-asset-6210df.s3.amazonaws.com/604405/241427770-d639f15b-0675-4561-9f24-708b767a7417.webm

here is the reproducer https://github.com/ozkanpakdil/swaggerific/blob/main/pom.xml#L28 I tried to apply https://stackoverflow.com/a/70413783/175554 but did not help.

version number I use **0.11.0**, main difference is I am using gluon graalvm as jdk , I installed it with sdkman.
```
sdk use java 22.1.0.1.r17-gln
```
below mvn java vsersion
```
$ mvn --version
Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)
Maven home: /home/oz-mint/.sdkman/candidates/maven/current
Java version: 17.0.3, vendor: GraalVM Community, runtime: /home/oz-mint/.sdkman/candidates/java/22.1.0.1.r17-gln
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-72-generic", arch: "amd64", family: "unix"
```
here is the full stacktrace
```
/home/oz-mint/.sdkman/candidates/java/22.1.0.1.r17-gln/bin/java -javaagent:/snap/intellij-idea-community/434/lib/idea_rt.jar=40681:/snap/intellij-idea-community/434/bin -Dfile.encoding=UTF-8 -classpath /home/oz-mint/.m2/repository/org/fxmisc/richtext/richtextfx/0.11.0/richtextfx-0.11.0.jar:/home/oz-mint/.m2/repository/org/reactfx/reactfx/2.0-M5/reactfx-2.0-M5.jar:/home/oz-mint/.m2/repository/org/fxmisc/undo/undofx/2.1.1/undofx-2.1.1.jar:/home/oz-mint/.m2/repository/org/fxmisc/flowless/flowless/0.7.0/flowless-0.7.0.jar:/home/oz-mint/.m2/repository/org/fxmisc/wellbehaved/wellbehavedfx/0.3.3/wellbehavedfx-0.3.3.jar:/home/oz-mint/.m2/repository/io/swagger/codegen/v3/swagger-codegen-maven-plugin/3.0.41/swagger-codegen-maven-plugin-3.0.41.jar:/home/oz-mint/.m2/repository/org/apache/maven/maven-core/3.2.5/maven-core-3.2.5.jar:/home/oz-mint/.m2/repository/org/apache/maven/maven-model/3.2.5/maven-model-3.2.5.jar:/home/oz-mint/.m2/repository/org/apache/maven/maven-settings/3.2.5/maven-settings-3.2.5.jar:/home/oz-mint/.m2/repository/org/apache/maven/maven-settings-builder/3.2.5/maven-settings-builder-3.2.5.jar:/home/oz-mint/.m2/repository/org/apache/maven/maven-repository-metadata/3.2.5/maven-repository-metadata-3.2.5.jar:/home/oz-mint/.m2/repository/org/apache/maven/maven-artifact/3.2.5/maven-artifact-3.2.5.jar:/home/oz-mint/.m2/repository/org/apache/maven/maven-model-builder/3.2.5/maven-model-builder-3.2.5.jar:/home/oz-mint/.m2/repository/org/apache/maven/maven-aether-provider/3.2.5/maven-aether-provider-3.2.5.jar:/home/oz-mint/.m2/repository/org/eclipse/aether/aether-spi/1.0.0.v20140518/aether-spi-1.0.0.v20140518.jar:/home/oz-mint/.m2/repository/org/eclipse/aether/aether-impl/1.0.0.v20140518/aether-impl-1.0.0.v20140518.jar:/home/oz-mint/.m2/repository/org/eclipse/aether/aether-api/1.0.0.v20140518/aether-api-1.0.0.v20140518.jar:/home/oz-mint/.m2/repository/org/eclipse/aether/aether-util/1.0.0.v20140518/aether-util-1.0.0.v20140518.jar:/home/oz-mint/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.plexus/0.3.0.M1/org.eclipse.sisu.plexus-0.3.0.M1.jar:/home/oz-mint/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar:/home/oz-mint/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar:/home/oz-mint/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.0.M1/org.eclipse.sisu.inject-0.3.0.M1.jar:/home/oz-mint/.m2/repository/org/sonatype/sisu/sisu-guice/3.2.3/sisu-guice-3.2.3-no_aop.jar:/home/oz-mint/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/home/oz-mint/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/home/oz-mint/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.21/plexus-interpolation-1.21.jar:/home/oz-mint/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar:/home/oz-mint/.m2/repository/org/codehaus/plexus/plexus-classworlds/2.5.2/plexus-classworlds-2.5.2.jar:/home/oz-mint/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar:/home/oz-mint/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar:/home/oz-mint/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar:/home/oz-mint/.m2/repository/org/apache/maven/maven-compat/3.2.5/maven-compat-3.2.5.jar:/home/oz-mint/.m2/repository/org/apache/maven/wagon/wagon-provider-api/2.8/wagon-provider-api-2.8.jar:/home/oz-mint/.m2/repository/org/apache/maven/maven-plugin-api/3.2.5/maven-plugin-api-3.2.5.jar:/home/oz-mint/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-annotations/3.4/maven-plugin-annotations-3.4.jar:/home/oz-mint/.m2/repository/io/swagger/codegen/v3/swagger-codegen/3.0.41/swagger-codegen-3.0.41.jar:/home/oz-mint/.m2/repository/io/swagger/swagger-parser/1.0.64/swagger-parser-1.0.64.jar:/home/oz-mint/.m2/repository/io/swagger/swagger-core/1.6.9/swagger-core-1.6.9.jar:/home/oz-mint/.m2/repository/io/swagger/swagger-models/1.6.9/swagger-models-1.6.9.jar:/home/oz-mint/.m2/repository/io/swagger/swagger-annotations/1.6.9/swagger-annotations-1.6.9.jar:/home/oz-mint/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar:/home/oz-mint/.m2/repository/io/swagger/parser/v3/swagger-parser/2.1.12/swagger-parser-2.1.12.jar:/home/oz-mint/.m2/repository/io/swagger/parser/v3/swagger-parser-v2-converter/2.1.12/swagger-parser-v2-converter-2.1.12.jar:/home/oz-mint/.m2/repository/io/swagger/parser/v3/swagger-parser-core/2.1.12/swagger-parser-core-2.1.12.jar:/home/oz-mint/.m2/repository/io/swagger/parser/v3/swagger-parser-v3/2.1.12/swagger-parser-v3-2.1.12.jar:/home/oz-mint/.m2/repository/io/swagger/swagger-codegen/2.4.30/swagger-codegen-2.4.30.jar:/home/oz-mint/.m2/repository/io/swagger/swagger-compat-spec-parser/1.0.64/swagger-compat-spec-parser-1.0.64.jar:/home/oz-mint/.m2/repository/com/github/java-json-tools/json-schema-validator/2.2.14/json-schema-validator-2.2.14.jar:/home/oz-mint/.m2/repository/com/github/java-json-tools/jackson-coreutils-equivalence/1.0/jackson-coreutils-equivalence-1.0.jar:/home/oz-mint/.m2/repository/com/github/java-json-tools/json-schema-core/1.2.14/json-schema-core-1.2.14.jar:/home/oz-mint/.m2/repository/com/github/java-json-tools/uri-template/0.10/uri-template-0.10.jar:/home/oz-mint/.m2/repository/org/mozilla/rhino/1.7.7.2/rhino-1.7.7.2.jar:/home/oz-mint/.m2/repository/com/sun/mail/mailapi/1.6.2/mailapi-1.6.2.jar:/home/oz-mint/.m2/repository/joda-time/joda-time/2.10.5/joda-time-2.10.5.jar:/home/oz-mint/.m2/repository/com/googlecode/libphonenumber/libphonenumber/8.11.1/libphonenumber-8.11.1.jar:/home/oz-mint/.m2/repository/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar:/home/oz-mint/.m2/repository/com/github/java-json-tools/json-patch/1.13/json-patch-1.13.jar:/home/oz-mint/.m2/repository/com/github/java-json-tools/msg-simple/1.2/msg-simple-1.2.jar:/home/oz-mint/.m2/repository/com/github/java-json-tools/btf/1.3/btf-1.3.jar:/home/oz-mint/.m2/repository/com/github/java-json-tools/jackson-coreutils/2.0/jackson-coreutils-2.0.jar:/home/oz-mint/.m2/repository/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar:/home/oz-mint/.m2/repository/org/apache/httpcomponents/httpcore/4.4.13/httpcore-4.4.13.jar:/home/oz-mint/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/home/oz-mint/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar:/home/oz-mint/.m2/repository/org/json/json/20220924/json-20220924.jar:/home/oz-mint/.m2/repository/com/samskivert/jmustache/1.15/jmustache-1.15.jar:/home/oz-mint/.m2/repository/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar:/home/oz-mint/.m2/repository/org/slf4j/slf4j-ext/1.7.36/slf4j-ext-1.7.36.jar:/home/oz-mint/.m2/repository/ch/qos/logback/logback-classic/1.2.10/logback-classic-1.2.10.jar:/home/oz-mint/.m2/repository/ch/qos/logback/logback-core/1.2.10/logback-core-1.2.10.jar:/home/oz-mint/.m2/repository/commons-cli/commons-cli/1.5.0/commons-cli-1.5.0.jar:/home/oz-mint/.m2/repository/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar:/home/oz-mint/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/home/oz-mint/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/home/oz-mint/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/home/oz-mint/.m2/repository/org/checkerframework/checker-qual/3.12.0/checker-qual-3.12.0.jar:/home/oz-mint/.m2/repository/com/google/errorprone/error_prone_annotations/2.7.1/error_prone_annotations-2.7.1.jar:/home/oz-mint/.m2/repository/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar:/home/oz-mint/.m2/repository/com/github/jknack/handlebars/4.3.1/handlebars-4.3.1.jar:/home/oz-mint/.m2/repository/org/commonmark/commonmark/0.17.0/commonmark-0.17.0.jar:/home/oz-mint/.m2/repository/io/swagger/codegen/v3/swagger-codegen-generators/1.0.38/swagger-codegen-generators-1.0.38.jar:/home/oz-mint/.m2/repository/io/swagger/core/v3/swagger-core/2.2.9/swagger-core-2.2.9.jar:/home/oz-mint/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/2.3.2/jakarta.xml.bind-api-2.3.2.jar:/home/oz-mint/.m2/repository/jakarta/activation/jakarta.activation-api/1.2.1/jakarta.activation-api-1.2.1.jar:/home/oz-mint/.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar:/home/oz-mint/.m2/repository/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar:/home/oz-mint/.m2/repository/io/swagger/core/v3/swagger-annotations/2.2.9/swagger-annotations-2.2.9.jar:/home/oz-mint/.m2/repository/jakarta/validation/jakarta.validation-api/2.0.2/jakarta.validation-api-2.0.2.jar:/home/oz-mint/.m2/repository/org/openjfx/javafx-base/19.0.2/javafx-base-19.0.2.jar:/home/oz-mint/.m2/repository/org/openjfx/javafx-controls/19.0.2/javafx-controls-19.0.2.jar:/home/oz-mint/.m2/repository/org/openjfx/javafx-graphics/19.0.2/javafx-graphics-19.0.2.jar:/home/oz-mint/.m2/repository/org/openjfx/javafx-fxml/19.0.2/javafx-fxml-19.0.2.jar:/home/oz-mint/.m2/repository/org/openjfx/javafx-web/19.0.2/javafx-web-19.0.2.jar:/home/oz-mint/.m2/repository/org/openjfx/javafx-media/19.0.2/javafx-media-19.0.2.jar -p /home/oz-mint/.m2/repository/org/yaml/snakeyaml/2.0/snakeyaml-2.0.jar:/home/oz-mint/.m2/repository/org/openjfx/javafx-controls/11/javafx-controls-11-win.jar:/home/oz-mint/.m2/repository/org/openjfx/javafx-controls/19.0.2/javafx-controls-19.0.2-linux.jar:/home/oz-mint/.m2/repository/org/openjfx/javafx-graphics/11/javafx-graphics-11-win.jar:/home/oz-mint/.m2/repository/org/openjfx/javafx-graphics/19.0.2/javafx-graphics-19.0.2-linux.jar:/home/oz-mint/.m2/repository/org/kordamp/ikonli/ikonli-core/12.3.1/ikonli-core-12.3.1.jar:/home/oz-mint/.m2/repository/org/openjfx/javafx-web/19.0.2/javafx-web-19.0.2-linux.jar:/home/oz-mint/.m2/repository/net/synedra/validatorfx/0.4.0/validatorfx-0.4.0.jar:/home/oz-mint/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.14.2/jackson-core-2.14.2.jar:/home/oz-mint/.m2/repository/org/kordamp/ikonli/ikonli-javafx/12.3.1/ikonli-javafx-12.3.1.jar:/home/oz-mint/.m2/repository/org/openjfx/javafx-base/11/javafx-base-11-win.jar:/home/oz-mint/.m2/repository/org/openjfx/javafx-base/11/javafx-base-11-linux.jar:/home/oz-mint/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.14.2/jackson-databind-2.14.2.jar:/home/oz-mint/.m2/repository/org/kordamp/bootstrapfx/bootstrapfx-core/0.4.0/bootstrapfx-core-0.4.0.jar:/home/oz-mint/.m2/repository/org/openjfx/javafx-media/19.0.2/javafx-media-19.0.2-linux.jar:/home/oz-mint/.m2/repository/org/controlsfx/controlsfx/11.1.2/controlsfx-11.1.2.jar:/home/oz-mint/.m2/repository/org/aspectj/aspectjrt/1.9.19/aspectjrt-1.9.19.jar:/home/oz-mint/.m2/repository/org/openjfx/javafx-fxml/11/javafx-fxml-11-win.jar:/home/oz-mint/.m2/repository/org/openjfx/javafx-fxml/19.0.2/javafx-fxml-19.0.2-linux.jar:/home/oz-mint/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.14.2/jackson-datatype-jsr310-2.14.2.jar:/home/oz-mint/projects/swaggerific/target/classes:/home/oz-mint/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.14.2/jackson-annotations-2.14.2.jar:/home/oz-mint/.m2/repository/com/dlsc/formsfx/formsfx-core/11.6.0/formsfx-core-11.6.0.jar:/home/oz-mint/.m2/repository/io/swagger/core/v3/swagger-models/2.2.9/swagger-models-2.2.9.jar:/home/oz-mint/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.14.2/jackson-dataformat-yaml-2.14.2.jar -m com.mascix.swaggerific/com.mascix.swaggerific.SwaggerApplication
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:409)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1082)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1082)
Caused by: java.lang.RuntimeException: No toolkit found
	at javafx.graphics/com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:409)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
	... 5 more

Process finished with exit code 1

```
how do I get that error [cinnamon-2023-05-30T193826+0100.webm](https://github.com/FXMisc/RichTextFX/assets/604405/f8902059-606f-41c4-b79c-e10362abffa3) so this is coming from intellij.

**Comment by ozkanpakdil** [comment]
I am closing this because this is more of IDE issue.
