### ISSUE TITLE
Question: InlineCssTextArea for appending 100 000 lines

### ISSUE THREAD

**Issue by PavelTurk** [FXMisc/RichTextFX#1208]
I need to use `InlineCssTextArea` for appending multiple lines (for example 100 000) with styles. For this I use the following code:

```
InlineCssTextArea textArea = ...
if (style == null) {
     textArea.appendText(text);
} else {
     textArea.append(text, style);
}
```
This code works, however it is very, very slow. I've found the following solution - https://github.com/FXMisc/RichTextFX/issues/121#issuecomment-76196547 but it is for `StyleClassedTextArea`, not for `InlineCssTextArea`. When I tried to use this solution for  `InlineCssTextArea` but to pass not CSS class name but CSS style string, I mean

```
StyleSpansBuilder<Collection<String>> ssb = new StyleSpansBuilder<>(texts.size());
...
sb.append(text);
ssb.add(Collections.singleton(style), text.length());

```
I got 

```
java.lang.ClassCastException: class java.util.Collections$SingletonSet cannot be cast to class java.lang.String (java.util.Collections$SingletonSet and java.lang.String are in module java.base of loader 'bootstrap')
	at org.fxmisc.richtext@0.10.9/org.fxmisc.richtext.StyledTextArea.createStyledTextNode(StyledTextArea.java:98) ~[richtextfx-0.10.9.jar:?]
	at org.fxmisc.richtext@0.10.9/org.fxmisc.richtext.StyledTextArea.createStyledTextNode(StyledTextArea.java:86) ~[richtextfx-0.10.9.jar:?]
	at org.fxmisc.richtext@0.10.9/org.fxmisc.richtext.StyledTextArea.lambda$new$0(StyledTextArea.java:35) ~[richtextfx-0.10.9.jar:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:5073) ~[?:?]
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:5081) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at org.fxmisc.richtext@0.10.9/org.fxmisc.richtext.ParagraphText.<init>(ParagraphText.java:153) ~[richtextfx-0.10.9.jar:?]
	at org.fxmisc.richtext@0.10.9/org.fxmisc.richtext.ParagraphBox.<init>(ParagraphBox.java:98) ~[richtextfx-0.10.9.jar:?]
	at org.fxmisc.richtext@0.10.9/org.fxmisc.richtext.GenericStyledArea.createCell(GenericStyledArea.java:1894) ~[richtextfx-0.10.9.jar:?]
	at org.fxmisc.richtext@0.10.9/org.fxmisc.richtext.GenericStyledArea.lambda$new$11(GenericStyledArea.java:765) ~[richtextfx-0.10.9.jar:?]
	at org.fxmisc.flowless@0.6.10/org.fxmisc.flowless.CellPool.getCell(CellPool.java:28) ~[flowless-0.6.10.jar:?]
	at org.fxmisc.flowless@0.6.10/org.fxmisc.flowless.CellListManager.cellForItem(CellListManager.java:99) ~[flowless-0.6.10.jar:?]
	at reactfx@2.0-M5/org.reactfx.collection.MappedList.get(MappedList.java:27) ~[reactfx-2.0-M5.jar:?]
	at reactfx@2.0-M5/org.reactfx.collection.MemoizationListImpl.get(MemoizationList.java:99) ~[reactfx-2.0-M5.jar:?]
	at org.fxmisc.flowless@0.6.10/org.fxmisc.flowless.CellListManager.getCell(CellListManager.java:77) ~[flowless-0.6.10.jar:?]
	at org.fxmisc.flowless@0.6.10/org.fxmisc.flowless.CellPositioner.getSizedCell(CellPositioner.java:217) ~[flowless-0.6.10.jar:?]
	at org.fxmisc.flowless@0.6.10/org.fxmisc.flowless.CellPositioner.placeStartAt(CellPositioner.java:127) ~[flowless-0.6.10.jar:?]
	at org.fxmisc.flowless@0.6.10/org.fxmisc.flowless.Navigator.visit(Navigator.java:134) ~[flowless-0.6.10.jar:?]
	at org.fxmisc.flowless@0.6.10/org.fxmisc.flowless.StartOffStart.accept(TargetPosition.java:85) ~[flowless-0.6.10.jar:?]
	at org.fxmisc.flowless@0.6.10/org.fxmisc.flowless.Navigator.layoutChildren(Navigator.java:80) ~[flowless-0.6.10.jar:?]
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1207) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at org.fxmisc.flowless@0.6.10/org.fxmisc.flowless.VirtualFlow.layoutChildren(VirtualFlow.java:257) ~[flowless-0.6.10.jar:?]
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1207) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at javafx.graphics/javafx.scene.Scene.doLayoutPass(Scene.java:579) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2499) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:405) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400) ~[?:?]
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:404) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:434) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:575) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:555) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:548) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:352) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316) ~[javafx-graphics-19-ea+3-linux.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

```

Could anyone say how to use InlineCssTextArea for appending 100 000 lines?

**Comment by Jugen** [comment]
When using `StyleSpansBuilder` for an `InlineCssTextArea` just add the style string as is without wrapping the style in a _Collections.singleton(style)_ like so: `ssb.add( style, text.length() );`
