### ISSUE TITLE
Pasting over a selection causes RichTextFX crash (version 0.9.1)

### ISSUE THREAD

**Issue by proudsalopian** [FXMisc/RichTextFX#783]
Steps:

1. Type "1"  (w/o quotes) into a RichTextFx control (CodeArea in my case, but I don't believe it matters)
2. Select the character using mouse or keyboard.
3. Paste "123"  (w/o quotes) over the selected charcter using CTRL+C shortcut.
4. The control crashes with java.lang.IllegalArgumentException caused by finalStart > finalEnd as calculated at

https://github.com/FXMisc/RichTextFX/blob/17a7957e585c8181fdc334673303229a5bc20410/richtextfx/src/main/java/org/fxmisc/richtext/SelectionImpl.java#L276

Partial trace:
Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException
	at javafx.scene.control.IndexRange.<init>(IndexRange.java:53)
	at org.fxmisc.richtext.SelectionImpl.selectRange(SelectionImpl.java:312)
	at org.fxmisc.richtext.SelectionImpl.lambda$new$7(SelectionImpl.java:276)

**Comment by proudsalopian** [comment]
Duplicate of [#774](https://github.com/FXMisc/RichTextFX/issues/774)
