### ISSUE TITLE
Exception thrown when listening to visible paragraphs property before the area is visible

### ISSUE THREAD

**Issue by garybentley** [FXMisc/RichTextFX#843]
The following exception is thrown if you add a listener to the visible paragraphs list before the area is actually visible.

```
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at java.base/java.util.Collections$UnmodifiableList.get(Collections.java:1308)
	at org.reactfx.util.Lists$2.get(Lists.java:181)
	at org.reactfx.collection.ChangeListenerWrapper$1.getFrom(LiveList.java:445)
	at javafx.base/javafx.collections.ListChangeListener$Change.wasAdded(ListChangeListener.java:188)
	at com.quollwriter.ui.fx.components.QSpellChecker.lambda$new$1(QSpellChecker.java:40)
	at org.reactfx.collection.ChangeListenerWrapper.onChange(LiveList.java:439)
	at org.reactfx.collection.ChangeListenerWrapper.onChange(LiveList.java:417)
	at org.reactfx.util.ListNotifications.lambda$takeHead$0(NotificationAccumulator.java:317)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.SuspendableBase.resume(SuspendableBase.java:64)
	at org.reactfx.CloseableOnceGuard.close(Guard.java:49)
	at org.reactfx.BiGuard.close(Guard.java:67)
	at org.reactfx.Suspendable$1.resumeSource(Suspendable.java:118)
	at org.reactfx.Suspendable$1.suspendSource(Suspendable.java:104)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.reactfx.EventStreams$3.lambda$observeInputs$0(EventStreams.java:105)
	at org.reactfx.value.ChangeListenerWrapper.accept(Val.java:786)
	at org.reactfx.util.AbstractReducingStreamNotifications.lambda$head$0(NotificationAccumulator.java:248)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.value.ValBase.invalidate(ValBase.java:32)
	at org.reactfx.SuspendableBoolean.release(SuspendableBoolean.java:24)
	at org.reactfx.CloseableOnceGuard.close(Guard.java:49)
	at org.reactfx.Suspendable.suspendWhile(Suspendable.java:49)
	at org.fxmisc.richtext.model.GenericEditableStyledDocumentBase.updateMulti(GenericEditableStyledDocumentBase.java:218)
	at org.fxmisc.richtext.model.GenericEditableStyledDocumentBase.updateSingle(GenericEditableStyledDocumentBase.java:210)
	at org.reactfx.util.Tuple3.exec(Tuple3.java:43)
	at org.fxmisc.richtext.model.GenericEditableStyledDocumentBase.replace(GenericEditableStyledDocumentBase.java:145)
	at org.fxmisc.richtext.model.GenericEditableStyledDocument.replace(GenericEditableStyledDocument.java:13)
	at org.fxmisc.richtext.GenericStyledArea.replace(GenericStyledArea.java:1212)
	at org.fxmisc.richtext.GenericStyledArea.replaceText(GenericStyledArea.java:1199)
	at org.fxmisc.richtext.EditActions.insertText(EditActions.java:32)
	at com.quollwriter.ui.fx.components.TextEditor.lambda$setText$3(TextEditor.java:154)
	at org.reactfx.Suspendable.suspendWhile(Suspendable.java:49)
	at com.quollwriter.ui.fx.components.TextEditor.setText(TextEditor.java:151)
```

The listener is:

```
        this.text.getVisibleParagraphs().addListener((javafx.collections.ListChangeListener<org.fxmisc.richtext.model.Paragraph<?, ?, ?>>) ev ->
        {

            if ((!ev.wasAdded())
                &&
                (!ev.wasRemoved())
               )
            {

                return;

            }

      });
```

My use case here is I'm trying to listen to when the visible paragraphs change so I can then run a spellchecker on them.  The [spell check demo](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/SpellCheckingDemo.java) rechecks the entire document every time there is a text change but I'd like to limit the amount of checking to just the visible paragraphs.

A lot of the issues I've been raising could probably be solved by having a property that indicates when the area is "ready" for use.  i.e. when the text is laid out and valid.  I could then trigger everything off of that property.

**Comment by Jugen** [comment]
I tried your code and it does throw the Exception you have provided, but that's because _ListChangeListener.Change_ requires you to call [next()](https://openjfx.io/javadoc/11/javafx.base/javafx/collections/ListChangeListener.Change.html#next()) before the other methods. I find it really annoying because it gets me every time as well ;-)  So your code should rather be something like:

```java
text.getVisibleParagraphs().addListener( (Change<? extends Paragraph> ch) ->
{
    // Note next() must be invoked first and then only the other methods !
    if ( ! ch.next() || ! (ch.wasAdded() || ch.wasRemoved()) ) return;

    // Spell check stuff ....
});
```

**Comment by garybentley** [comment]
Good catch, thanks.  I hate the way that listener works, not a good design choice to me and it's not the first time I've been caught out with it.

After some testing I've had to ditch the visible paragraphs idea because changing the style on some text in the paragraph (i.e. marking some text as a spelling error) will then trigger a change in the visible paragraphs list, probably because Paragraph is immutable so a new one is being created.  Of course this triggers my listener again and it goes off into an infinite loop.  

I'm now just listening to the plainTextChanges stream instead which seems to work.
