### ISSUE TITLE
If line highlighting is on then get exception if caret is outside of viewport

### ISSUE THREAD

**Issue by garybentley** [FXMisc/RichTextFX#937]
I'm getting the following exception:

```
java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Optional.java:148)
        at org.fxmisc.flowless.CellListManager.getPresentCell(CellListManager.java:65)
        at org.fxmisc.flowless.CellPositioner.getVisibleCell(CellPositioner.java:33)
        at org.fxmisc.flowless.Navigator.distanceFromGround(Navigator.java:373)
        at org.fxmisc.flowless.Navigator.fillViewportFrom(Navigator.java:333)
        at org.fxmisc.flowless.Navigator.visit(Navigator.java:131)
        at org.fxmisc.flowless.StartOffStart.accept(TargetPosition.java:85)
        at org.fxmisc.flowless.Navigator.layoutChildren(Navigator.java:80)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1206)
        at org.fxmisc.flowless.VirtualFlow.layoutChildren(VirtualFlow.java:257)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1206)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1213)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1213)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1213)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1213)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1213)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1213)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1213)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1213)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1213)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1213)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1213)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1213)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1213)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1213)
        at javafx.graphics/javafx.scene.Scene.doLayoutPass(Scene.java:576)
        at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2482)

```
This occurs when I first create the area, wrapped in a VirtualizedScrollPane, and setLineHighlightingOn is set to true before any text is added to the area.  If I then add text that is rendered larger than the viewport height (i.e. by having a high font size) then I get the exception above.   I'm not calling area.requestFollowCaret so I don't think that's the cause.  If I don't have the line highlighting switched on then I don't get the exception for the same text/font size.

**Comment by Jugen** [comment]
Hi Gary, I can't seem to replicate this issue. Can you please supply a simple demo program that reliably produces the exception.

**Comment by garybentley** [comment]
I'll see if I can.  My code has ballooned in size now that it's nearing completion.

**Comment by garybentley** [comment]
So doing some more detailed tests I think the issue actually lies with the layout of the viewport.  If the caret is on the last line of the viewport and I press "Enter" then a new line is added (new paragraph) but the caret is not positioned at the bottom of the viewport, you can still scroll down a few pixels.  This is at a font size of 12pt.  If you increase the font size, say to 40pt and then repeat the process, only about a third of the caret is visible and most of the new line is actually outside of the viewport.

I tried to get a picture of this but I haven't found a way to set the blink rate of the caret, doing area.getCaretSelectionBind().setBlinkRate doesn't seem to be working.

However I've added a picture with the writing line highlighted.

![caret-big-text1](https://user-images.githubusercontent.com/921991/90300782-90678c80-dedf-11ea-9eaa-b428ba875c65.jpg)

In the image above, I had the caret on the last line of the viewport, I pressed "Enter" and the caret moved down but the viewport didn't scroll fully to make the line fully visible.  You can see the small gap at the bottom of the vertical scrollbar on the right.

The image below shows the last line fully scrolled into view (I moved it manually)

![caret-big-text2](https://user-images.githubusercontent.com/921991/90300853-d9b7dc00-dedf-11ea-9d28-ae704ebc1e60.jpg)

If the text area is empty and I press enter repeatedly then the first line that moves below the bottom of the viewport is fine but the second new line at the bottom of the viewport shows the problem.

A further issue that I'll mention here rather than creating a new issue is that if the caret is at the start of the line and I press "Del" on my keyboard rather than "Backspace" then the writing line highlight will often disappear until I press another key.

**Comment by Jugen** [comment]
Okay, so I was able to replicate the incomplete line problem you described above and have submitted a PR to fix it.

Also experienced the "Del" line highlighting issue, and will have a look at that tomorrow.

Still haven't encountered the NoSuchElementException though ?  Can you please verify the fix I've submitted so far and if you still encounter the Exception.

**Comment by garybentley** [comment]
The PR fixes the incomplete line problem, thanks.  I'm still getting the NoSuchElementException, I'm currently trying to create a reproducible example.

I have a few other issues with the line highlighter though.  I have a reproducible example for those, essentially just do:

```
StyleClassedTextArea area = new StyleClassedTextArea ();
area.setLineHighlighterOn (true);
area.setWrapText (true);
try { 
  area.insert (0, new String (Files.readAllBytes (Paths.get ("ipsum.txt")), StandardCharsets.UTF_8), "text");
} catch (Exception e) { e.printStackTrace (); }
VirtualizedScrollPane<StyleClassedTextArea> vsPane = new VirtualizedScrollPane<>(area);
VBox vbox = new VBox();
VBox.setVgrow(vsPane, Priority.ALWAYS);
vbox.getChildren().addAll(vsPane);
Scene scene = new Scene(vbox, 600, 400);
s.setScene (scene);
s.show ();
```

I've attached the ipsum.txt file, it just contains a large amount of lorem ipsum text.
[ipsum.txt](https://github.com/FXMisc/RichTextFX/files/5094009/ipsum.txt)

If setWrapText is true then the line highlight (scroll to the bottom of the area) is a line above the caret.

If setWrapText is false then the line highlight behaves strangely and will often be on the line above the caret.  Also if you scroll the area horizontally the highlight won't stretch the entire length of the area, it seems to be a fixed width equal to the width of the viewport.

**Comment by Jugen** [comment]
The "lorem ipsum" problem has been fixed (in above PR) as well as an NPE problem I encountered along the way (in another PR). Could you please try the current "snapshot" out and see if you still get the NoSuchElementException ..... thanks.

**Comment by garybentley** [comment]
Yes those fixes seem to solve the NPE issue and the NoSuchElementException, at least I now don't see it when I try to reproduce the circumstances.  Thanks.
