### ISSUE TITLE
NullPointerException occurs when resizing after text is changed using getTotalHeightEstimate 

### ISSUE THREAD

**Issue by xulihang** [FXMisc/RichTextFX#997]
Here is my test code:

```java
import javafx.application.Application;
import javafx.scene.Scene;
import org.fxmisc.richtext.CodeArea;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

public class Test extends Application {

	 @Override
	    public void start(Stage primaryStage) throws Exception {
	        AnchorPane root = new AnchorPane();
	        CodeArea ta = new CodeArea();
	        root.getChildren().add(ta);
	        AnchorPane.setLeftAnchor(ta, 5.0);
	        AnchorPane.setTopAnchor(ta, 5.0);
	        ta.setPrefSize(100, 100);
	        ta.setStyle("-fx-font-size:18; -fx-font-family: Arial;-fx-border-color: blue;-fx-border-width: 1 ;");
	        ta.setWrapText(true);
	        ta.textProperty().addListener(
	        	    (observable, oldvalue, newvalue) ->
	        	        resize(ta)
	        	    );
	        primaryStage.setScene(new Scene(root, 100, 150));
	        primaryStage.show();
	    }
	    
	    private void resize(CodeArea ta){
    	    try{
    	        ta.setPrefHeight(ta.getTotalHeightEstimate());
    	    } 
    	    catch (Exception e) {
    			//System.out.println(e.getMessage());
    	    	e.printStackTrace();
    		};
	    }
	 
	    public static void main(String[] args) {
	        launch(args);
	    }
}

```

Exception when I just input a charater:

```
at org.fxmisc.flowless.Virtualized.getTotalHeightEstimate(Virtualized.java:17)
	at fx.Test.resize(Test.java:31)
	at fx.Test.lambda$0(Test.java:23)
	at org.reactfx.value.ChangeListenerWrapper.accept(Val.java:786)
	at org.reactfx.util.AbstractReducingStreamNotifications.lambda$head$0(NotificationAccumulator.java:248)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.SuspendableBase.resume(SuspendableBase.java:64)
	at org.reactfx.CloseableOnceGuard.close(Guard.java:49)
	at org.reactfx.MultiGuard.close(Guard.java:83)
	at org.reactfx.Suspendable$1.resumeSource(Suspendable.java:118)
	at org.reactfx.Suspendable$1.suspendSource(Suspendable.java:104)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.reactfx.EventStreams$3.lambda$observeInputs$0(EventStreams.java:105)
	at org.reactfx.value.ChangeListenerWrapper.accept(Val.java:786)
	at org.reactfx.util.AbstractReducingStreamNotifications.lambda$head$0(NotificationAccumulator.java:248)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.value.ValBase.invalidate(ValBase.java:32)
	at org.reactfx.SuspendableBoolean.release(SuspendableBoolean.java:24)
	at org.reactfx.CloseableOnceGuard.close(Guard.java:49)
	at org.reactfx.Suspendable.suspendWhile(Suspendable.java:49)
	at org.fxmisc.richtext.model.GenericEditableStyledDocumentBase.updateMulti(GenericEditableStyledDocumentBase.java:218)
	at org.fxmisc.richtext.model.GenericEditableStyledDocumentBase.updateSingle(GenericEditableStyledDocumentBase.java:210)
	at org.reactfx.util.Tuple3.exec(Tuple3.java:43)
	at org.fxmisc.richtext.model.GenericEditableStyledDocumentBase.replace(GenericEditableStyledDocumentBase.java:145)
	at org.fxmisc.richtext.model.SimpleEditableStyledDocument.replace(SimpleEditableStyledDocument.java:10)
	at org.fxmisc.richtext.GenericStyledArea.replace(GenericStyledArea.java:1403)
	at org.fxmisc.richtext.GenericStyledArea.replaceText(GenericStyledArea.java:1390)
	at org.fxmisc.richtext.TextEditingArea.replaceText(TextEditingArea.java:396)
	at org.fxmisc.richtext.EditActions.replaceSelection(EditActions.java:179)
	at org.fxmisc.richtext.GenericStyledAreaBehavior.keyTyped(GenericStyledAreaBehavior.java:354)
	at org.fxmisc.wellbehaved.event.template.InputMapTemplate.lambda$consume$0(InputMapTemplate.java:221)
	at org.fxmisc.wellbehaved.event.template.PatternActionTemplate.lambda$null$1(InputMapTemplate.java:425)
	at java.util.Optional.map(Optional.java:215)
	at org.fxmisc.wellbehaved.event.template.PatternActionTemplate.lambda$getInputHandlerTemplateMap$2(InputMapTemplate.java:425)
	at org.fxmisc.wellbehaved.event.template.InputMapTemplate$1.lambda$null$0(InputMapTemplate.java:202)
	at org.fxmisc.wellbehaved.event.template.InputMapTemplate$2.lambda$null$0(InputMapTemplate.java:341)
	at org.fxmisc.wellbehaved.event.template.InputMapTemplate$HandlerTemplateConsumer$1.lambda$accept$0(InputMapTemplate.java:103)
	at org.fxmisc.wellbehaved.event.InputHandler.handle(InputHandler.java:50)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$KeyHandler.process(Scene.java:3964)
	at javafx.scene.Scene$KeyHandler.access$1800(Scene.java:3910)
	at javafx.scene.Scene.impl_processKeyEvent(Scene.java:2040)
	at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2501)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
	at com.sun.glass.ui.View.handleKeyEvent(View.java:546)
	at com.sun.glass.ui.View.notifyKey(View.java:966)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by xulihang** [comment]
I found the property AutoHeight. This code works fine.

```java
package fx;

import org.fxmisc.richtext.CodeArea;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

public class Test extends Application {

	 @Override
	    public void start(Stage primaryStage) throws Exception {
	        AnchorPane root = new AnchorPane();
	        CodeArea ta = new CodeArea();
	        root.getChildren().add(ta);
	        AnchorPane.setLeftAnchor(ta, 5.0);
	        AnchorPane.setTopAnchor(ta, 5.0);
	        ta.replaceText("This is a sentence.");
	        ta.setStyle("-fx-font-size:18; -fx-font-family: Arial;-fx-border-color: blue;-fx-border-width: 1 ;");
	        ta.setWrapText(true);
	        ta.setAutoHeight(true);
	        primaryStage.setScene(new Scene(root, 100, 150));
	        primaryStage.show();
	    }
	    
	    public static void main(String[] args) {
	        launch(args);
	    }
}

```
